<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'fastest/fastest';
    const VERSIONS = array (
  'composer/semver' => '1.4.2@c7cb9a2095a074d131b65a8a0cd294479d785573',
  'composer/xdebug-handler' => '1.1.0@c919dc6c62e221fc6406f861ea13433c0aa24f08',
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'egulias/email-validator' => '2.1.4@8790f594151ca6a2010c6218e09d96df67173ad3',
  'erusev/parsedown' => '1.7.1@92e9c27ba0e74b8b028b111d1b6f956a15c01fc1',
  'friendsofphp/php-cs-fixer' => 'v2.12.1@beef6cbe6dec7205edcd143842a49f9a691859a6',
  'guzzlehttp/psr7' => '1.4.2@f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
  'intervention/image' => '2.4.2@e82d274f786e3d4b866a59b173f42e716f0783eb',
  'kriswallsmith/assetic' => 'v1.4.0@e911c437dbdf006a8f62c2f59b15b2d69a5e0aa1',
  'league/flysystem' => '1.0.45@a99f94e63b512d75f851b181afcdf0ee9ebef7e6',
  'league/uri' => '5.3.0@f2bceb755f1108758cf4cf925e4cd7699ce686aa',
  'league/uri-components' => '1.8.0@5290537e2d3bc5218d4aa4cc62d277a7e01050b5',
  'league/uri-hostname-parser' => '1.1.1@7a6be3d06d0ed08dcb51f666aa60f3b66cd51325',
  'league/uri-interfaces' => '1.1.0@b5063ffb8b129923c8988f1d4061fdeea53b47b9',
  'league/uri-manipulations' => '1.5.0@ae8d49a3203ccf7a1e39aaf7fae9f08bfbc454a2',
  'league/uri-parser' => '1.4.0@8beb28540744a5ad728aee7060100002f9196f46',
  'league/uri-schemes' => '1.2.0@c26aedac0f60d1ce915aa309e1d08a4b09c7d708',
  'lnked/pubsub' => 'dev-master@1b4c3e25e9e37e8de6024ef9fd7f20241f21a34c',
  'lnked/q' => 'dev-master@22e159461b5b4bca29bc1a2c7e1f034ee3a599a8',
  'matthiasmullie/minify' => '1.3.60@ab7fea80ce5ce6549baaf272bc8bd926a7e08f90',
  'matthiasmullie/path-converter' => '1.1.1@3082a6838be02b930239a97d38b5c9da4d693aca',
  'matthiasmullie/scrapbook' => '1.4.6@044ff954e41579ff922ee3341b1695d12bb04840',
  'mthaml/mthaml' => '1.8.0@b7e0c72883ee3efcf8b8819210b90496158b00d4',
  'paragonie/random_compat' => 'v2.0.15@10bcb46e8f3d365170f6de9d05245aa066b81f09',
  'php-cs-fixer/diff' => 'v1.3.0@78bb099e9c16361126c86ce82ec4405ebab8e756',
  'phpfastcache/phpfastcache' => '6.1.3@a1edf28ae8d847b692b6bee8cae867398ff7d2f2',
  'phpoffice/phpspreadsheet' => '1.3.1@aa5b0d0236c907fd8dba0883f3ceb97cc52e46ec',
  'prewk/xml-streamer' => '0.5.0@d375929a7d96b9dc0246af270209465c7dd4de5b',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'samdark/sitemap' => '2.2.0@c897f7a9cb0882e34169359a5f1f715e05b34d67',
  'smarty/smarty' => 'v3.1.32@ac9d4b587e5bf53381e21881820a9830765cb459',
  'spomky-labs/base64url' => 'v1.0.2@ef6d5fb93894063d9cee996022259fd08d6646ea',
  'swiftmailer/swiftmailer' => 'v6.0.2@412333372fb6c8ffb65496a2bbd7321af75733fc',
  'symfony/console' => 'v3.4.12@1b97071a26d028c9bd4588264e101e14f6e7cd00',
  'symfony/debug' => 'v3.4.12@47e6788c5b151cf0cfdf3329116bf33800632d75',
  'symfony/event-dispatcher' => 'v3.4.12@fdd5abcebd1061ec647089c6c41a07ed60af09f8',
  'symfony/filesystem' => 'v3.4.12@8a721a5f2553c6c3482b1c5b22ed60fe94dd63ed',
  'symfony/finder' => 'v3.4.12@3a8c3de91d2b2c68cd2d665cf9d00f7ef9eaa394',
  'symfony/options-resolver' => 'v3.4.12@cc5e98ed91688a22a7162a8800096356f9076b1d',
  'symfony/polyfill-ctype' => 'v1.8.0@7cc359f1b7b80fc25ed7796be7d96adc9b354bae',
  'symfony/polyfill-iconv' => 'v1.8.0@7cb8436a814d5b0fcf292810ee26f8b0cb47584d',
  'symfony/polyfill-intl-grapheme' => 'v1.8.0@f30a9fb355ef8cc7411caf8da7c59b4e2db137fe',
  'symfony/polyfill-intl-normalizer' => 'v1.8.0@00fad3a3e2db93a2b788d83dfdd432a3c7e8fb4f',
  'symfony/polyfill-mbstring' => 'v1.8.0@3296adf6a6454a050679cde90f95350ad604b171',
  'symfony/polyfill-php70' => 'v1.8.0@77454693d8f10dd23bb24955cffd2d82db1007a6',
  'symfony/polyfill-php72' => 'v1.8.0@a4576e282d782ad82397f3e4ec1df8e0f0cafb46',
  'symfony/process' => 'v3.4.12@acc5a37c706ace827962851b69705b24e71ca17c',
  'symfony/stopwatch' => 'v3.4.12@eb17cfa072cab26537ac37e9c4ece6c0361369af',
  'twig/twig' => 'v2.4.8@7b604c89da162034bdf4bb66310f358d313dd16d',
  'vlucas/phpdotenv' => 'v2.4.0@3cc116adbe4b11be5ec557bf1d24dc5e3a21d18c',
  'voku/portable-utf8' => '5.0.6@d591208c292c9a603131e0169bf1da7cd179b417',
  'voronkovich/sberbank-acquiring-client' => 'v1.1.3@7c0148166b7cb7117a95b16c4b77e58be5e5ade6',
  'zircote/swagger-php' => '2.0.13@8b42fdc3d8c5a5e0d1f8d344aa359822c9f085e0',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'jean85/pretty-package-versions' => '1.2@75c7effcf3f77501d0e0caa75111aff4daa0dd48',
  'myclabs/deep-copy' => '1.8.1@3e01bdad3e18354c3dce54466b7fbe33a9f9f7f8',
  'nette/bootstrap' => 'v2.4.6@268816e3f1bb7426c3a4ceec2bd38a036b532543',
  'nette/di' => 'v2.4.13@3f8f212b02d5c17feb97a7e0a39ab306f40c06ca',
  'nette/finder' => 'v2.4.2@ee951a656cb8ac622e5dd33474a01fd2470505a0',
  'nette/neon' => 'v2.4.3@5e72b1dd3e2d34f0863c5561139a19df6a1ef398',
  'nette/php-generator' => 'v3.0.4@b381ecacbf5a0b5f99cc0b303d5b0578d409f446',
  'nette/robot-loader' => 'v3.0.4@3cf88781a05e0bf4618ae605361afcbaa4d5b392',
  'nette/utils' => 'v2.5.2@183069866dc477fcfbac393ed486aaa6d93d19a5',
  'nikic/php-parser' => 'v3.1.5@bb87e28e7d7b8d9a7fda231d37457c9210faf6ce',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'paquettg/php-html-parser' => '1.7.0@18845e09831dd0772b88b51e788a4f74c701224c',
  'paquettg/string-encode' => '0.1.1@cf08343649701979f581c1601d01247fa3782439',
  'phar-io/manifest' => '1.0.1@2df402786ab5368a0169091f61a7c1e0eb6852d0',
  'phar-io/version' => '1.0.1@a70c0ced4be299a63d32fa96d9281d03e94041df',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.0@94fd0001232e47129dd3504189fa1c7225010d08',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.7.6@33a7e3c4fda54e912ff6338c48823bd5c0f0b712',
  'phpstan/phpdoc-parser' => '0.2@02f909f134fe06f0cd4790d8627ee24efbe84d6a',
  'phpstan/phpstan' => '0.9.2@e59541bcc7cac9b35ca54db6365bf377baf4a488',
  'phpunit/dbunit' => '3.0.3@0fa4329e490480ab957fe7b1185ea0996ca11f44',
  'phpunit/php-code-coverage' => '5.3.2@c89677919c5dd6d3b3852f230a663118762218ac',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '2.0.2@791198a2c6254db10131eecfe8c06670700904db',
  'phpunit/phpunit' => '6.5.8@4f21a3c6b97c42952fd5c2837bb354ec0199b97b',
  'phpunit/phpunit-mock-objects' => '5.0.7@3eaf040f20154d27d6da59ca2c6e28ac8fd56dce',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '2.1.3@34369daee48eafb2651bea869b4b15d75ccc35f9',
  'sebastian/diff' => '2.0.1@347c1d8b49c5c3ee30c7040ea6fc446790e6bddd',
  'sebastian/environment' => '3.1.0@cd0871b3975fb7fc44d11314fd1ee20925fce4f5',
  'sebastian/exporter' => '3.1.0@234199f4528de6d12aaa58b612e98f7d36adb937',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'squizlabs/php_codesniffer' => '3.3.0@d86873af43b4aa9d1f39a3601cc0cfcf02b25266',
  'symfony/yaml' => 'v3.4.12@c5010cc1692ce1fa328b1fb666961eb3d4a85bb0',
  'theseer/tokenizer' => '1.1.0@cb2f008f3f05af2893a87208fe6a6c4985483f8b',
  'webmozart/assert' => '1.3.0@0df1908962e7a3071564e857d86874dad1ef204a',
  'fastest/fastest' => 'dev-dev@1f160ed4039e2d025b643b0b4c0764195c6f6306',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
