<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'stringEncode' => array($vendorDir . '/paquettg/string-encode/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'PHPHtmlParser' => array($vendorDir . '/paquettg/php-html-parser/src'),
    'MtHaml\\' => array($vendorDir . '/mthaml/mthaml/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
